/*
 * QueryResponse.kt
 *
 * This code was generated by json-kotlin-schema-codegen - JSON Schema Code Generator
 * See https://github.com/pwall567/json-kotlin-schema-codegen
 *
 * It is not advisable to modify generated code as any modifications will be lost
 * when the generation process is re-run.
 */
package com.lock.lockassistant.model.intents.query

import java.util.UUID

/**
 * This intent queries for the current states of devices. It is used for queries where truly real-time accuracy is required (for example, the status of a door lock). Only states are returned when action.devices.QUERY is triggered. To update the properties or traits or other persistent elements of the device, action.devices.SYNC is used.
 */
data class QueryResponse(
    /** ID of the corresponding request. */
    val requestId: UUID,
    /** Intent response payload. */
    val payload: Payload
) {

    /**
     * Intent response payload.
     */
    data class Payload(
        /** An error code for the entire transaction for auth failures and developer system unavailability. For individual device errors use the errorCode within the device object. */
        val errorCode: String? = null,
        /** Detailed error which will never be presented to users but may be logged or used during development. */
        val debugString: String? = null,
        /** Map of devices. Maps developer device ID to object of state properties. */
        val devices: Devices
    )

    /**
     * Map of devices. Maps developer device ID to object of state properties.
     */
    open class Devices

}
