server:
  port: 9000
  ssl:
    key-store-type: PKCS12
    key-store: src/main/resources/keystore/lockassistant.p12
    key-store-password: lockassistant
    key-alias: lockassistant
logging:
  level:
    net.pwall.json.schema.codegen: DEBUG
